name: database_bridge
description: A unified Flutter database service wrapper supporting SQL (Drift, Sqflite), NoSQL (Hive, ObjectBox), and secure storage with a consistent API

version: 1.0.1

repository: https://github.com/mustafa-fahimi/database_bridge
homepage: https://github.com/mustafa-fahimi/database_bridge
issue_tracker: https://github.com/mustafa-fahimi/database_bridge/issues
documentation: https://github.com/mustafa-fahimi/database_bridge#readme

topics:
  - database
  - flutter
  - sql
  - nosql
  - storage

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  objectbox: ^5.1.0
  objectbox_flutter_libs: ^5.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.7+1
  sqflite_common_ffi_web: ^1.0.1+1

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  objectbox_generator: ^5.1.0
